export { apiFacercgGET } from './apiFacercgGET'
export { apiImgholderGET } from './apiImgholderGET'
export { apiIpGET } from './apiIpGET'
export { apiKFCCrazyThursdayGET } from './apiKFCCrazyThursdayGET'
export { apiPixelArtPOST } from './apiPixelArtPOST'
export { apiQrcodeGET } from './apiQrcodeGET'
export { apiTranslateGET } from './apiTranslateGET'
