export { apiFacercgGET } from './apiFacercgGET'
export { apiImgholderGET } from './apiImgholderGET'
export { apiIpGET } from './apiIpGET'
export { apiKFCCrazyThursdayGET } from './apiKFCCrazyThursdayGET'
export { apiPixelArtPOST } from './PixelArt/api'
export { apiQrcodeGET } from './apiQrcodeGET'
export { apiTranslateGET } from './apiTranslateGET'
export { apiWebstackScreenshotGET } from './WebstackScreenshot/api'